### ISSUE TITLE
Question: kill container after connection was interrupted (docker-compose)

### ISSUE THREAD

**Issue by capc0** [jdenoy/ike-docker#1]
Hi, first of all thank you for providing this image with the character fix!

I am currently using the image in a docker compose setup

```yml
version: "3"
services:
  vpnclient:
    image: jdenoy/ike
    command: site.vpn
    volumes:
      - ./sites:/sites
    privileged: true
    network_mode: "host"
    # restart: always

``` 

When the VPN tunnel is terminated, it would be nice if the container would stop/shut down automatically.

So e.g. when the following occurs

```
2021-09-08T13:15:04.454886206Z K! : unhandled pfkey message type EXPI!! : session terminated by gateway
2021-09-08T13:15:04.455015411Z ii : tunnel disabled
2021-09-08T13:15:04.455858636Z >> : detached from key daemon
```

Can you guide me in the correct way to be able to achieve this?

I would then use the `restart` field of docker compose in order to re-establish broken VPN connections 24/7.

Thanks.
